
package wsCancelacion40;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCancelacion40Service", targetNamespace = "http://wservicios/", wsdlLocation = "http://dev33.facturacfdi.mx:80/WSCancelacion40Service?wsdl")
public class WSCancelacion40Service
    extends Service
{

    private final static URL WSCANCELACION40SERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCANCELACION40SERVICE_EXCEPTION;
    private final static QName WSCANCELACION40SERVICE_QNAME = new QName("http://wservicios/", "WSCancelacion40Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev33.facturacfdi.mx:80/WSCancelacion40Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCANCELACION40SERVICE_WSDL_LOCATION = url;
        WSCANCELACION40SERVICE_EXCEPTION = e;
    }

    public WSCancelacion40Service() {
        super(__getWsdlLocation(), WSCANCELACION40SERVICE_QNAME);
    }

    public WSCancelacion40Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCANCELACION40SERVICE_QNAME, features);
    }

    public WSCancelacion40Service(URL wsdlLocation) {
        super(wsdlLocation, WSCANCELACION40SERVICE_QNAME);
    }

    public WSCancelacion40Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCANCELACION40SERVICE_QNAME, features);
    }

    public WSCancelacion40Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCancelacion40Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCancelacion40
     */
    @WebEndpoint(name = "WSCancelacion40Port")
    public WSCancelacion40 getWSCancelacion40Port() {
        return super.getPort(new QName("http://wservicios/", "WSCancelacion40Port"), WSCancelacion40.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns WSCancelacion40
     */
    @WebEndpoint(name = "WSCancelacion40Port")
    public WSCancelacion40 getWSCancelacion40Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservicios/", "WSCancelacion40Port"), WSCancelacion40.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCANCELACION40SERVICE_EXCEPTION!= null) {
            throw WSCANCELACION40SERVICE_EXCEPTION;
        }
        return WSCANCELACION40SERVICE_WSDL_LOCATION;
    }

}
